gw_dbt_model:
  outputs:
    dev:
      account: yiwjnxp-wu74685
      database: DEV_CURATED_DB
      password: "{{ env_var('SNOWFLAKE_KEY_PASS') }}"
      role: SFG_DEV_DATA_ENGINEER
      schema: L001_GWPC
      threads: 4
      type: snowflake
      user: afshin
      warehouse: dev_etl_wh
  target: dev