with cte_data as 
(
SELECT 
  $1:DONOTDESTROY::BOOLEAN as donotdestroy,
  $1:ISPORTALPOLICY_ICARE::BOOLEAN as isportalpolicy_icare,
  $1:PUBLICID::TEXT as publicid,
  $1:PRIORPREMIUMS::NUMBER as priorpremiums,
  $1:ISSUEDATE::TIMESTAMP_LTZ as issuedate,
  $1:PRIORPREMIUMS_CUR::NUMBER as priorpremiums_cur,
  $1:MOVEDPOLICYSOURCEACCOUNTID::NUMBER as movedpolicysourceaccountid,
  $1:ACCOUNTID::NUMBER as accountid,
  $1:CREATETIME::TIMESTAMP_LTZ as createtime,
  $1:LOSSHISTORYTYPE::NUMBER as losshistorytype,
  $1:EXCLUDEDFROMARCHIVE::BOOLEAN as excludedfromarchive,
  $1:ARCHIVESTATE::NUMBER as archivestate,
  $1:ARCHIVESCHEMAINFO::NUMBER as archiveschemainfo,
  $1:ARCHIVEFAILUREDETAILSID::NUMBER as archivefailuredetailsid,
  $1:PACKAGERISK::NUMBER as packagerisk,
  $1:NUMPRIORLOSSES::NUMBER as numpriorlosses,
  $1:UPDATETIME::TIMESTAMP_LTZ as updatetime,
  $1:PRIMARYLANGUAGE::NUMBER as primarylanguage,
  $1:DONOTARCHIVE::BOOLEAN as donotarchive,
  $1:ID::NUMBER as id,
  $1:PRIMARYLOCALE::NUMBER as primarylocale,
  $1:PRODUCTCODE::TEXT as productcode,
  $1:EXCLUDEREASON::TEXT as excludereason,
  $1:GROUPNUMBERFROMPORTAL::NUMBER as groupnumberfromportal,
  $1:CREATEUSERID::NUMBER as createuserid,
  $1:ARCHIVEFAILUREID::NUMBER as archivefailureid,
  $1:CRNNUMBER_ICARE::TEXT as crnnumber_icare,
  $1:ORIGINALEFFECTIVEDATE::TIMESTAMP_LTZ as originaleffectivedate,
  $1:BEANVERSION::NUMBER as beanversion,
  $1:ARCHIVEPARTITION::NUMBER as archivepartition,
  $1:RETIRED::NUMBER as retired,
  $1:UPDATEUSERID::NUMBER as updateuserid,
  $1:PRIORTOTALINCURRED::NUMBER as priortotalincurred,
  $1:ARCHIVEDATE::TIMESTAMP_LTZ as archivedate,
  $1:PRIORTOTALINCURRED_CUR::NUMBER as priortotalincurred_cur,
  $1:PRODUCERCODEOFSERVICEID::NUMBER as producercodeofserviceid,
  $1:NEWPRODUCERCODE_EXT::NUMBER as newproducercode_ext,
  $1:NEWCLAIMSCHEMEAGENT_ICARE::NUMBER as newclaimschemeagent_icare,
  $1:MOVEDPOLSRCACCTPUBID::TEXT as movedpolsrcacctpubid,
  $1:CURRENT_RECORD_FLAG::BOOLEAN as current_record_flag,
  $1:AGENCYCONTACTDETAILS_EXT::TEXT as agencycontactdetails_ext,
  $1:AGENCYCONTACTEMAIL_EXT::TEXT as agencycontactemail_ext,
  $1:AGENCYCONTACTNUMBER_EXT::TEXT as agencycontactnumber_ext,
  $1:INSURANCEBOOK_EXTID::NUMBER as insurancebook_extid
FROM {{ source('gwpc', 'RAW_PC_POLICY') }}
)

SELECT 
    donotdestroy,
    isportalpolicy_icare,
    publicid,
    priorpremiums,
    issuedate,
    priorpremiums_cur,
    movedpolicysourceaccountid,
    accountid,
    createtime,
    losshistorytype,
    excludedfromarchive,
    archivestate,
    archiveschemainfo,
    archivefailuredetailsid,
    packagerisk,
    numpriorlosses,
    updatetime,
    primarylanguage,
    donotarchive,
    id,
    primarylocale,
    productcode,
    excludereason,
    groupnumberfromportal,
    createuserid,
    archivefailureid,
    crnnumber_icare,
    originaleffectivedate,
    beanversion,
    archivepartition,
    retired,
    updateuserid,
    priortotalincurred,
    archivedate,
    priortotalincurred_cur,
    producercodeofserviceid,
    newproducercode_ext,
    newclaimschemeagent_icare,
    movedpolsrcacctpubid,
    current_record_flag,
    agencycontactdetails_ext,
    agencycontactemail_ext,
    agencycontactnumber_ext,
    insurancebook_extid,
    {{ dbt_utils.generate_surrogate_key([
        'donotdestroy',
        'isportalpolicy_icare',
        'publicid',
        'priorpremiums',
        'issuedate',
        'priorpremiums_cur',
        'movedpolicysourceaccountid',
        'accountid',
        'createtime',
        'losshistorytype',
        'excludedfromarchive',
        'archivestate',
        'archiveschemainfo',
        'archivefailuredetailsid',
        'packagerisk',
        'numpriorlosses',
        'updatetime',
        'primarylanguage',
        'donotarchive',
        'primarylocale',
        'productcode',
        'excludereason',
        'groupnumberfromportal',
        'createuserid',
        'archivefailureid',
        'crnnumber_icare',
        'originaleffectivedate',
        'beanversion',
        'archivepartition',
        'retired',
        'updateuserid',
        'priortotalincurred',
        'archivedate',
        'priortotalincurred_cur',
        'producercodeofserviceid',
        'newproducercode_ext',
        'newclaimschemeagent_icare',
        'movedpolsrcacctpubid',
        'current_record_flag',
        'agencycontactdetails_ext',
        'agencycontactemail_ext',
        'agencycontactnumber_ext',
        'insurancebook_extid',
        'ID'
    ]) }} sys_unique_id
FROM cte_data
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY updatetime) = 1
